name: Rust Format and Test

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt -- --check
    - name: Test
      run: cargo test
